routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('masters', 'MasterController');

Route::resource('journals', 'JournalController');

Route::resource('schedules', 'ScheduleController');

Route::resource('masters', 'MasterController');

Route::resource('posts', 'PostController');

Route::resource('categories', 'CategoryController');

Route::resource('masterServices', 'MasterServiceController');

Route::resource('services', 'ServiceController');

Route::resource('clients', 'ClientController');

Route::resource('resources', 'ResourceController');

Route::resource('companies', 'CompanyController');

app/Models/MasterService.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class MasterService
 * @package App\Models
 * @version November 21, 2018, 10:49 pm PKT
 *
 * @property Master master
 * @property Service service
 * @property \Illuminate\Database\Eloquent\Collection journalsServices
 * @property \Illuminate\Database\Eloquent\Collection masters
 * @property \Illuminate\Database\Eloquent\Collection journals
 * @property integer master_id
 * @property integer service_id
 * @property integer percent
 * @property integer money
 */
class MasterService extends Model
{
    use SoftDeletes;

    public $table = 'master_service';

    protected $dateFormat = 'Y-m-d H:i:sP';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'master_id',
        'service_id',
        'percent',
        'money'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'master_id' => 'integer',
        'service_id' => 'integer',
        'percent' => 'integer',
        'money' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function master()
    {
        return $this->belongsTo(Master::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function service()
    {
        return $this->belongsTo(Service::class);
    }
}

app/Http/Controllers/MasterServiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMasterServiceRequest;
use App\Http\Requests\UpdateMasterServiceRequest;
use App\Models\Master;
use App\Models\Service;
use App\Repositories\MasterServiceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class MasterServiceController extends AppBaseController
{
    /** @var  MasterServiceRepository */
    private $masterServiceRepository;

    public function __construct(MasterServiceRepository $masterServiceRepo)
    {
        $this->masterServiceRepository = $masterServiceRepo;
    }

    /**
     * Display a listing of the MasterService.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->masterServiceRepository->pushCriteria(new RequestCriteria($request));
        $masterServices = $this->masterServiceRepository->all();

        return view('master_services.index')
            ->with('masterServices', $masterServices);
    }

    /**
     * Show the form for creating a new MasterService.
     *
     * @return Response
     */
    public function create()
    {
        $masters = Master::all()->pluck('name', 'id');
        $services = Service::all()->pluck('name', 'id');

        return view('master_services.create')->with(compact('masters', 'services'));
    }

    /**
     * Store a newly created MasterService in storage.
     *
     * @param CreateMasterServiceRequest $request
     *
     * @return Response
     */
    public function store(CreateMasterServiceRequest $request)
    {
        $input = $request->all();

        $masterService = $this->masterServiceRepository->create($input);

        Flash::success('Master Service saved successfully.');

        return redirect(route('masterServices.index'));
    }

    /**
     * Display the specified MasterService.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $masterService = $this->masterServiceRepository->findWithoutFail($id);

        if (empty($masterService)) {
            Flash::error('Master Service not found');

            return redirect(route('masterServices.index'));
        }

        return view('master_services.show')->with('masterService', $masterService);
    }

    /**
     * Show the form for editing the specified MasterService.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $masterService = $this->masterServiceRepository->findWithoutFail($id);

        if (empty($masterService)) {
            Flash::error('Master Service not found');

            return redirect(route('masterServices.index'));
        }
        $masters = Master::all()->pluck('name', 'id');
        $services = Service::all()->pluck('name', 'id');
        return view('master_services.edit')->with(compact('masterService', 'masters', 'services'));
    }

    /**
     * Update the specified MasterService in storage.
     *
     * @param  int              $id
     * @param UpdateMasterServiceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMasterServiceRequest $request)
    {
        $masterService = $this->masterServiceRepository->findWithoutFail($id);

        if (empty($masterService)) {
            Flash::error('Master Service not found');

            return redirect(route('masterServices.index'));
        }

        $masterService = $this->masterServiceRepository->update($request->all(), $id);

        Flash::success('Master Service updated successfully.');

        return redirect(route('masterServices.index'));
    }

    /**
     * Remove the specified MasterService from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $masterService = $this->masterServiceRepository->findWithoutFail($id);

        if (empty($masterService)) {
            Flash::error('Master Service not found');

            return redirect(route('masterServices.index'));
        }

        $this->masterServiceRepository->delete($id);

        Flash::success('Master Service deleted successfully.');

        return redirect(route('masterServices.index'));
    }
}

resources/views/master_services/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {{ __('Master Service') }}
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'masterServices.store']) !!}
                        @include('master_services.fields')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/master_services/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {{ __('Master Service') }}
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($masterService, ['route' => ['masterServices.update', $masterService->id], 'method' => 'patch']) !!}
                        @include('master_services.fields')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/master_services/fields.blade.php
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('master_id', __('Master Id').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::select('master_id', $masters, null, ['class' => 'form-control']) !!}
    </div>
</div>


<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('service_id', __('Service Id').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::select('service_id', $services, null, ['class' => 'form-control']) !!}
    </div>
</div>


<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('percent', __('Percent').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::number('percent', null, ['class' => 'form-control']) !!}
    </div>
</div>


<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('money', __('Money').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::number('money', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group col-sm-12">
    <div class="col-sm-9 col-sm-offset-3">
    {!! Form::submit(__('Save'), ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('masterServices.index') !!}" class="btn btn-default">{{ __('Cancel') }}</a>
    </div>
</div>

resources/views/master_services/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">{{ __('Master Services') }}</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('masterServices.create') !!}">{{ __('Add New') }}</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('master_services.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/master_services/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {{ __('Master Service') }}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('master_services.show_fields')
                    <a href="{!! route('masterServices.index') !!}" class="btn btn-default">{{ __('Back') }}</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/master_services/show_fields.blade.php
<div class="form-group">
    {!! Form::label('id', __('Id:')) !!}
    {!! $masterService->id !!}
</div>


<div class="form-group">
    {!! Form::label('master_id', __('Master Id:')) !!}
    {!! $masterService->master !!}
</div>


<div class="form-group">
    {!! Form::label('service_id', __('Service Id:')) !!}
    {!! $masterService->service !!}
</div>


<div class="form-group">
    {!! Form::label('percent', __('Percent:')) !!}
    {!! $masterService->percent !!}
</div>


<div class="form-group">
    {!! Form::label('money', __('Money:')) !!}
    {!! $masterService->money !!}
</div>


<div class="form-group">
    {!! Form::label('deleted_at', __('Deleted At:')) !!}
    {!! $masterService->deleted_at !!}
</div>


<div class="form-group">
    {!! Form::label('created_at', __('Created At:')) !!}
    {!! $masterService->created_at !!}
</div>


<div class="form-group">
    {!! Form::label('updated_at', __('Updated At:')) !!}
    {!! $masterService->updated_at !!}
</div>

resources/views/master_services/table.blade.php
<table class="table table-responsive" id="masterServices-table">
    <thead>
        <tr>
            <th>{{ __('Master Id') }}</th>

        <th>{{ __('Service Id') }}</th>

        <th>{{ __('Percent') }}</th>

        <th>{{ __('Money') }}</th>

            <th colspan="3">{{ __('Action') }} </th>
        </tr>
    </thead>
    <tbody>
    @foreach($masterServices as $masterService)
        <tr>
            <td>{!! $masterService->master_id !!}</td>
            <td>{!! $masterService->service_id !!}</td>
            <td>{!! $masterService->percent !!}</td>
            <td>{!! $masterService->money !!}</td>
            <td>
                {!! Form::open(['route' => ['masterServices.destroy', $masterService->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('masterServices.show', [$masterService->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('masterServices.edit', [$masterService->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('". __('Are you sure?')."')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>