routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('masters', 'MasterController');

Route::resource('journals', 'JournalController');

Route::resource('schedules', 'ScheduleController');

Route::resource('masters', 'MasterController');

Route::resource('posts', 'PostController');

Route::resource('categories', 'CategoryController');

Route::resource('masterServices', 'MasterServiceController');

Route::resource('services', 'ServiceController');

Route::resource('clients', 'ClientController');

Route::resource('resources', 'ResourceController');

Route::resource('companies', 'CompanyController');

app/Models/Master.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Master
 * @package App\Models
 *
 * @property Post post
 * @property Category category
 * @property \Illuminate\Database\Eloquent\Collection journalsServices
 * @property \Illuminate\Database\Eloquent\Collection MasterService
 * @property \Illuminate\Database\Eloquent\Collection Journal
 * @property string name
 * @property string surname
 * @property integer post_id
 * @property integer category_id
 * @property boolean is_master
 * @property boolean online
 * @property boolean use_mintime
 */
class Master extends Model
{
    use SoftDeletes;

    protected $dateFormat = 'Y-m-d H:i:sP';

    public $table = 'masters';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $dates = ['deleted_at'];


    public $fillable = [
        'name',
        'surname',
        'post_id',
        'category_id',
        'is_master',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'surname' => 'string',
        'post_id' => 'integer',
        'category_id' => 'integer',
        'is_master' => 'boolean',
        'online' => 'boolean',
        'use_mintime' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function getIsMasterAttribute($attribute)
    {
        return $attribute ? __('Yes') : __('No');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function schedules()
    {
        return $this->hasMany(Schedule::class, 'masters_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function masterServices()
    {
        return $this->hasMany(MasterService::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function journals()
    {
        return $this->hasMany(Journal::class);
    }

    public function getTitleAttribute()
    {
        return $this->name. ' '.$this->surname;
    }
}

app/Models/Schedule.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Schedule
 * @package App\Models
 *
 * @property Master master
 * @property \Illuminate\Database\Eloquent\Collection journalsServices
 * @property \Illuminate\Database\Eloquent\Collection masterService
 * @property \Illuminate\Database\Eloquent\Collection masters
 * @property \Illuminate\Database\Eloquent\Collection journals
 * @property timetz work_from
 * @property timetz work_to
 * @property timetz lunch_from
 * @property timetz launch_to
 * @property boolean launch
 * @property datetimetz date
 * @property integer masters_id
 */
class Schedule extends Model
{
    use SoftDeletes;

    public $table = 'schedules';

    protected $dateFormat = 'Y-m-d H:i:sP';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $dates = ['deleted_at'];

    public $fillable = [
        'work_from',
        'work_to',
        'lunch_from',
        'launch_to',
        'launch',
        'date',
        'masters_id'
    ];

    private function formatTime($time)
    {
        return isset($time) ? Carbon::createFromFormat('H:i:sP', $time)->format('H:i') : null;
    }

    public function getWorkFromAttribute($time)
    {
        return $this->formatTime($time);
    }

    public function getWorkToAttribute($time)
    {
        return $this->formatTime($time);
    }

    public function getLaunchToAttribute($time)
    {
        return $this->formatTime($time);
    }

    public function getLaunchFromAttribute($time)
    {
        return $this->formatTime($time);
    }

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'launch' => 'boolean',
        'date' => 'date',
        'masters_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function master()
    {
        return $this->belongsTo(Master::class, 'masters_id');
    }
}

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateScheduleRequest;
use App\Http\Requests\UpdateScheduleRequest;
use App\Models\Master;
use App\Models\Schedule;
use App\Repositories\ScheduleRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class ScheduleController extends AppBaseController
{
    /** @var  ScheduleRepository */
    private $scheduleRepository;

    public function __construct(ScheduleRepository $scheduleRepo)
    {
        $this->scheduleRepository = $scheduleRepo;
    }

    /**
     * Display a listing of the Schedule.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->scheduleRepository->pushCriteria(new RequestCriteria($request));
        $schedules = $this->scheduleRepository->all();

        $masters = Master::all()->pluck('id', 'name');
        return view('schedules.index')->with(compact('schedules', 'masters'));
    }

    /**
     * Show the form for creating a new Schedule.
     *
     * @return Response
     */
    public function create()
    {
        $masters = Master::all()->pluck('name', 'id');

        return view('schedules.create')->with(compact('masters'));
    }

    /**
     * Store a newly created Schedule in storage.
     *
     * @param CreateScheduleRequest $request
     *
     * @return Response
     */
    public function store(CreateScheduleRequest $request)
    {
        $input = $request->all();

        $schedule = $this->scheduleRepository->create($input);

        Flash::success(__('Schedule saved successfully.'));

        return redirect(route('schedules.index'));
    }

    /**
     * Display the specified Schedule.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $schedule = $this->scheduleRepository->findWithoutFail($id);

        if (empty($schedule)) {
            Flash::error(__('Schedule not found'));

            return redirect(route('schedules.index'));
        }

        return view('schedules.show')->with('schedule', $schedule);
    }

    /**
     * Show the form for editing the specified Schedule.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $schedule = $this->scheduleRepository->findWithoutFail($id);

        if (empty($schedule)) {
            Flash::error(__('Schedule not found'));

            return redirect(route('schedules.index'));
        }
        $masters = Master::all()->pluck('name', 'id');

        return view('schedules.edit')->with(compact('schedule', 'masters'));
    }

    /**
     * Update the specified Schedule in storage.
     *
     * @param  int              $id
     * @param UpdateScheduleRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateScheduleRequest $request)
    {
        $schedule = $this->scheduleRepository->findWithoutFail($id);

        if (empty($schedule)) {
            Flash::error(__('Schedule not found'));

            return redirect(route('schedules.index'));
        }

        $schedule = $this->scheduleRepository->update($request->all(), $id);

        Flash::success(__('Schedule updated successfully.'));

        return redirect(route('schedules.index'));
    }

    /**
     * Remove the specified Schedule from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $schedule = $this->scheduleRepository->findWithoutFail($id);

        if (empty($schedule)) {
            Flash::error(__('Schedule not found'));

            return redirect(route('schedules.index'));
        }

        $this->scheduleRepository->delete($id);

        Flash::success(__('Schedule deleted successfully.'));

        return redirect(route('schedules.index'));
    }
}

resources/views/schedules/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {{ __('Schedule') }}
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'schedules.store']) !!}
                        @include('schedules.fields')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/schedules/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! __('Schedule') !!}
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($schedule, ['route' => ['schedules.update', $schedule->id], 'method' => 'patch']) !!}
                        @include('schedules.fields')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/schedules/fields.blade.php
<div class="form-group col-sm-6">
    {!! Form::label('work_from', __('Work From').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::time('work_from', null, ['class' => 'form-control']) !!}
    </div>
</div>


<div class="form-group col-sm-6">
    {!! Form::label('work_to', __('Work To').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::time('work_to', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('launch', __('Launch').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::hidden('launch', 0) !!}
        {!! Form::checkbox('launch', '1') !!}
    </div>
</div>

<div class="form-group col-sm-6">
    {!! Form::label('lunch_from', __('Lunch From').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::time('lunch_from', null, ['class' => 'form-control']) !!}
    </div>
</div>


<div class="form-group col-sm-6">
    {!! Form::label('launch_to', __('Launch To').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::time('launch_to', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('date', __('Date').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::date('date', $schedule->date, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('masters_id', __('Masters Id').':', ['class' => 'col-sm-3 control-label text-right']) !!}
    <div class="col-sm-9 col-md-6 col-lg-6">
        {!! Form::select('masters_id', $masters, null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group col-sm-12">
    <div class="col-sm-9 col-sm-offset-3">
    {!! Form::submit(__('Save'), ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('schedules.index') !!}" class="btn btn-default">{!! __('Cancel') !!}</a>
    </div>
</div>

resources/views/schedules/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">{{ __('Schedules') }}</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('schedules.create') !!}">{{ __('Add New') }}</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('schedules.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/schedules/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! __('Schedule') !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('schedules.show_fields')
                    <a href="{!! route('schedules.index') !!}" class="btn btn-default">{!! __('Back') !!}</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/schedules/show_fields.blade.php
<div class="form-group">
    {!! Form::label('id', __('Id').':') !!}
    {!! $schedule->id !!}
</div>

<div class="form-group">
    {!! Form::label('work_from', __('Work From').':') !!}
    {!! $schedule->work_from !!}
</div>

<div class="form-group">
    {!! Form::label('work_to', __('Work To').':') !!}
    {!! $schedule->work_to !!}
</div>

<div class="form-group">
    {!! Form::label('lunch_from', __('Lunch From').':') !!}
    {!! $schedule->lunch_from !!}
</div>

<div class="form-group">
    {!! Form::label('launch_to', __('Launch To').':') !!}
    {!! $schedule->launch_to !!}
</div>

<div class="form-group">
    {!! Form::label('launch', __('Launch').':') !!}
    {!! $schedule->launch !!}
</div>

<div class="form-group">
    {!! Form::label('date', __('Date').':') !!}
    {!! $schedule->date !!}
</div>

<div class="form-group">
    {!! Form::label('masters_id', __('Masters Id').':') !!}
    {!! $schedule->master->title !!}
</div>

<div class="form-group">
    {!! Form::label('deleted_at', __('Deleted At').':') !!}
    {!! $schedule->deleted_at !!}
</div>

<div class="form-group">
    {!! Form::label('created_at', __('Created At').':') !!}
    {!! $schedule->created_at !!}
</div>

<div class="form-group">
    {!! Form::label('updated_at', __('Updated At').':') !!}
    {!! $schedule->updated_at !!}
</div>

resources/views/schedules/table.blade.php
<table class="table table-responsive" id="schedules-table">
    <thead>
        <tr>
            <th>{{ __('Work From') }}</th>
            <th>{{ __('Work To') }}</th>
            <th>{{ __('Lunch From') }}</th>
            <th>{{ __('Launch To') }}</th>
            <th>{{ __('Launch') }}</th>
            <th>{{ __('Date') }}</th>
            <th>{{ __('Masters Id') }}</th>
            <th colspan="3">{!! __('Action') !!} </th>
        </tr>
    </thead>
    <tbody>
    @foreach($schedules as $schedule)
        <tr>
            <td>{!! $schedule->work_from !!}</td>
            <td>{!! $schedule->work_to !!}</td>
            <td>{!! $schedule->lunch_from !!}</td>
            <td>{!! $schedule->launch_to !!}</td>
            <td>{!! $schedule->launch !!}</td>
            <td>{!! $schedule->date !!}</td>
            <td>{!! $schedule->master->title !!}</td>
            <td>
                {!! Form::open(['route' => ['schedules.destroy', $schedule->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('schedules.show', [$schedule->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('schedules.edit', [$schedule->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('". __('Are you sure?')."')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>